insert into products (name, category, unit_price) values ('Cauliflower Pizza Crust', 'Food - Frozen Foods', 933.11);
insert into products (name, category, unit_price) values ('Pineapple Coconut Rice Mix', 'Food - Grains', 357.77);
insert into products (name, category, unit_price) values ('Smoky BBQ Jackfruit', 'Food - Grocery', 844.5);
insert into products (name, category, unit_price) values ('Kitchen Knife Sharpening System', 'Kitchen', 770.15);
insert into products (name, category, unit_price) values ('Car Vacuum Cleaner', 'Automotive', 19.53);
insert into products (name, category, unit_price) values ('Non-Stick Grill Pan', 'Kitchen', 444.88);
insert into products (name, category, unit_price) values ('Cinnamon Apple Sauce', 'Food - Canned Goods', 677.16);
insert into products (name, category, unit_price) values ('Pesto Genovese', 'Food - Condiments', 454.16);
insert into products (name, category, unit_price) values ('Self-Stirring Mug', 'Kitchen', 649.12);
insert into products (name, category, unit_price) values ('Fitness Smartwatch', 'Wearable Tech', 290.82);
insert into products (name, category, unit_price) values ('Electric Heat Pad', 'Health', 901.74);
insert into products (name, category, unit_price) values ('Coconut Chia Pudding', 'Food - Dairy', 786.47);
insert into products (name, category, unit_price) values ('Garlic Parmesan Roasted Nuts', 'Food - Nuts', 619.81);
insert into products (name, category, unit_price) values ('Collapsible Pet Dog Bowl', 'Pets', 526.32);
insert into products (name, category, unit_price) values ('Vegetarian Stir Fry Sauce', 'Food - Condiments', 271.35);
insert into products (name, category, unit_price) values ('USB Wall Charger', 'Accessories', 848.25);
insert into products (name, category, unit_price) values ('Pet Reflective Vest', 'Pets', 978.53);
insert into products (name, category, unit_price) values ('Phone Case', 'Accessories', 858.87);
insert into products (name, category, unit_price) values ('Car Vacuum Cleaner', 'Automotive', 465.77);
insert into products (name, category, unit_price) values ('Ceramic Non-Stick Frying Pan', 'Kitchen', 252.72);
insert into products (name, category, unit_price) values ('Tea Infuser Bottle', 'Kitchen', 860.42);
insert into products (name, category, unit_price) values ('Bamboo Toothbrush Holder', 'Health', 248.66);
insert into products (name, category, unit_price) values ('Apple Cinnamon Granola', 'Food - Breakfast', 668.83);
insert into products (name, category, unit_price) values ('Sun-Dried Tomato Pesto', 'Food - Condiments', 837.96);
insert into products (name, category, unit_price) values ('Safety Goggles', 'Safety', 527.71);
insert into products (name, category, unit_price) values ('Garden Kneeler and Seat', 'Garden', 618.95);
insert into products (name, category, unit_price) values ('Backpacking Tent', 'Outdoor', 792.62);
insert into products (name, category, unit_price) values ('Portable Dog Water Bottle', 'Pets', 661.17);
insert into products (name, category, unit_price) values ('Portable Hammock Swing', 'Outdoor', 474.81);
insert into products (name, category, unit_price) values ('Oven-Baked Chicken Tenders', 'Food - Meat', 445.53);
insert into products (name, category, unit_price) values ('Emergency Preparedness Kit', 'Safety', 280.9);
insert into products (name, category, unit_price) values ('Portable USB-C Monitor', 'Electronics', 480.99);
insert into products (name, category, unit_price) values ('Reflective Safety Vest', 'Safety', 451.08);
insert into products (name, category, unit_price) values ('Garden Tool Set with Carrying Bag', 'Garden', 994.87);
insert into products (name, category, unit_price) values ('Mini Air Hockey Table', 'Toys', 894.89);
insert into products (name, category, unit_price) values ('Skincare Fridge', 'Beauty', 366.73);
insert into products (name, category, unit_price) values ('Classic Bagels', 'Food - Bakery', 460.92);
insert into products (name, category, unit_price) values ('Bamboo Bathtub Caddy', 'Home', 217.09);
insert into products (name, category, unit_price) values ('Sous Vide Cooker', 'Kitchen', 100.65);
insert into products (name, category, unit_price) values ('Pet Carrier', 'Pets', 366.76);
insert into products (name, category, unit_price) values ('Leather Crossbody Bag', 'Clothing - Bags', 485.44);
insert into products (name, category, unit_price) values ('Homestyle Beef Stew', 'Food - Canned Soups', 218.04);
insert into products (name, category, unit_price) values ('Fitness Mat', 'Fitness', 83.86);
insert into products (name, category, unit_price) values ('Asian Salad Mix', 'Food - Produce', 400.36);
insert into products (name, category, unit_price) values ('Set of Silicone Cooking Utensils', 'Kitchen', 782.67);
insert into products (name, category, unit_price) values ('Classic Pumps', 'Clothing - Footwear', 239.53);
insert into products (name, category, unit_price) values ('Travel Pillow with Memory Foam', 'Travel', 390.17);
insert into products (name, category, unit_price) values ('Cabbage', 'Food - Produce', 946.6);
insert into products (name, category, unit_price) values ('Frozen Burritos', 'Food - Frozen Foods', 241.9);
insert into products (name, category, unit_price) values ('Eco-Friendly Cleaning Cloths', 'Home', 39.33);
